"""scheduler

Revision ID: e6f7a07cca8c
Revises: 30a94684c7d1
Create Date: 2025-12-24 09:04:14.939415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f7a07cca8c'
down_revision: Union[str, Sequence[str], None] = '30a94684c7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_recurring', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('recurring_period_days', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('next_run', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'next_run')
    op.drop_column('transactions', 'recurring_period_days')
    op.drop_column('transactions', 'is_recurring')
    # ### end Alembic commands ###
